name: Ruby on Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Ruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2 # Specify your Ruby version
        bundler-cache: true

    # Install dependencies
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    # Set up database
    - name: Set up database
      run: |
        cp config/database.yml.ci config/database.yml
        bundle exec rails db:prepare

    # Run tests
    - name: Run tests
      run: |
        bundle exec rspec # or `bundle exec rails test` if using Minitest

